services:
  gameserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}:/gameserver/data
      - ./banned_words.txt:/gameserver/banned_words.txt

    ports:
      - "${PORT}:${PORT}"